export  const GET_USERS_START = 'GET_USERS_START';
export  const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export  const GET_USERS_FAILURE = 'GET_USERS_FAILURE';
export  const CREATE_USERS_START = 'CREATE_USERS_START';
export  const CREATE_USERS_SUCCESS = 'CREATE_USERS_SUCCESS';
export  const CREATE_USERS_FAILURE = 'CREATE_USERS_FAILURE';